version: '3'

services:
  # Servicio de la API
  api:
    build: .   # Ubicación del Dockerfile (actualmente en el mismo directorio)
    ports:
      - "443:443"   # Mapeo del puerto del contenedor al puerto del host
    depends_on:
      - mongodb   # Indicamos que depende del servicio 'mongodb'

  # Servicio de MongoDB
  mongodb:
    image: mongo:latest   # Utilizamos la imagen oficial de MongoDB desde Docker Hub
    ports:
      - "27017:27017"   # Mapeo del puerto del contenedor al puerto del host
    volumes:
      - mongo_data:/data/db   # Mapeo de volumen para persistir los datos

volumes:
  mongo_data:   # Definimos el volumen para MongoDB
